package o20170301;

public class In2Throw {
	public static void main(String[] args) {
		int a = 100;
		
//		if (a>60) {
//			// 这个即为异常
//			throw new Exception("数据大于60，不符合条件");
//		}
		
//		try {
//			// 自定义的条件异常
//			if (a>60) {
//				// 这个即为异常
//				throw new Exception("数据大于60，不符合条件");
//			}
//		}catch(Exception e) {
//			System.out.println("当前捕获的异常是：" + e);
//		}
		
		// 系统默认调出来的
		
//		if (a>60) {
//			try {
//				throw new Exception("数据大于60，不符合条件");
//			} catch (Exception e) {
//				// TODO Auto-generated catch block
//				e.printStackTrace();
//			}
//		}
		
		
		
	}
}
